version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Athens"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    target-branch: "dependabot/github-actions"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Athens"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "javascript"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    target-branch: "dependabot/npm"
    versioning-strategy: "increase-if-necessary"
    